<template>
  <PolygonjsScene
    :sceneName="'scene_01'"
    :loadFunction="loadFunction"
    :autoPlay="true"
    :displayLoadingProgressBar="true"
    :posterExtension="'webp'"
    publicPath=""
  />
</template>

<script lang="ts">
import { defineComponent, computed } from "vue";
import PolygonjsScene from "./PolygonjsScene.vue";
import { loadSceneAndMountAsync_scene_01 } from "@/polygonjs/scenes/scene_01/autogenerated/loadSceneAndMountAsync";

export default defineComponent({
  name: "scene-01",

  components: {
    PolygonjsScene,
  },
  setup(props) {
    const loadFunction = computed(() => loadSceneAndMountAsync_scene_01);

    return {
      loadFunction,
    };
  },
});
</script>
